name: Copy_Secrets

permissions:
  contents: write
  actions: write

on: 
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repo Name (e.g. MyRepo)'
        required: true
        default: ''
      team:
        description: 'Team Name'
        required: false
        default: 'XiGeoAlgorithm'

jobs:
  copy_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: copy-secrets
        uses: gendloop/copy-secrets@main
        with: 
          repo: ${{ inputs.repo }}
          team: ${{ inputs.team }}
          token: ${{ secrets.GENDLOOP_ACCESS_TOKEN }}

      